【斗篷设置】:
  广告地址: 'ad.html' # 填写./page文件夹中的页面，或直接填写网站链接(链接将通过301跳转过去)
  模式: "正常"  # 正常/广告  正常模式下所有请求默认返回正常页面，广告模式下所有请求默认返回广告页面
  正常模式:
    搜索来路跳广告: True # True/False 开启后所有从搜索引擎(谷歌/必应/百度/搜狗/360)过来的请求，全部直接返回广告页ad.html
    指定IP段跳广告: '168.168.168.*|88.88.88.88'
    指定地区跳广告: '中国|香港|局域网'
  广告模式:
    指定IP段跳文章页: '168.168.168.*|88.88.88.88'
    指定地区跳文章页: '中国|香港'
  
【安全策略】: # 屏蔽指定的UA头和IP段，防止恶意访问
  UA黑名单: 'Scrapy|Curl|HttpClient|UniversalFeedParser|lightDeckReports Bot|heritrix|Java|Bytespider|YandexBot|FlightDeckReports|Indy Library|BOT/0.1|DigExt|Feedly|Swiftbot|oBot|Python-urllib|CrawlDaddy|YYSpider|JikeSpider|ZmEu|MJ12bot|WebZIP|Apache-HttpAsyncClient|HttpClient|WinHttp|jaunty|Alexa Toolbar|LinkpadBot|Microsoft URL Control|node-superagent|Ezooms|Jullo|SemrushBot|FetchURL|AhrefsBot|EasouSpider|java/|CoolpadWebkit|Linguee Bot|ApacheBench|AskTbFXTV|FeedDemon'
  IP黑名单: '168.168.168.*|88.88.88.88'

【蜘蛛策略】:
  蜘蛛看的页面: 'index.html'  # 这里填写./page文件夹中的页面，用于搜索引擎收录
  蜘蛛开关: # 关闭的蜘蛛直接返回404
    谷歌蜘蛛: true
    谷歌图片蜘蛛: false
    百度蜘蛛: true
    搜狗蜘蛛: true
    神马蜘蛛: true
    头条蜘蛛: true
    必应蜘蛛: true
    360蜘蛛: true
    雅虎蜘蛛: true
    其它蜘蛛: false
    其他蜘蛛: false

【Telegram机器人】: # telegram机器人设置后，将定时发送服务器状态至telegram群组
  Bot-Token: 'Bot-Token'
  群组ID: ''